# Generated by Django 2.1.7 on 2019-05-18 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0002_auto_20190518_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='book',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='apiv1.Book'),
        ),
    ]
