# Generated by Django 2.1.7 on 2019-05-20 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0004_auto_20190520_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell', to='apiv1.Book'),
        ),
    ]
